---
# Syncronisation des fichiers de configuration et certificats
- name: Slurp certificates from /etc/kubernetes/pki
  slurp:
    src: /etc/kubernetes/pki/{{ item }}
  loop:
    - ca.crt
    - ca.key
    - apiserver.key
    - apiserver.crt
#   - apiserver-kubelet-client.crt
#   - apiserver-kubelet-client.key
#   - front-proxy-ca.crt
#   - front-proxy-ca.key
#   - front-proxy-client.crt
#   - front-proxy-client.key
    - sa.key
    - sa.pub
  register: certificates
  run_once: true
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Copy certificates on all nodes
  copy:
    content: "{{ item.content | b64decode }}"
    dest: /etc/kubernetes/pki/{{ item.item }}
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ certificates.results }}"

- name: Slurp configurations from /etc/kubernetes
  slurp:
    src: /etc/kubernetes/{{ item }}.conf
  loop:
    - admin
#   - kubelet
    - scheduler
    - controller-manager
  register: configurations
  run_once: true
  delegate_to: "{{ groups['k8s_masters'][0] }}"

- name: Copy configurations on all nodes
  copy:
    content: "{{ item.content | b64decode }}"
    dest: /etc/kubernetes/{{ item.item }}.conf
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ configurations.results }}"