---
- include_tasks: 01-certificates.yml

- include_tasks: 02-configurations.yml

- include_tasks: 03-sync-files.yml

- include_tasks: 04-services.yml

- name: kubectl configuration
  file:
    path: /root/.kube
    state: directory

- name: kubectl configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes